###Register a new user
POST http://localhost:5000/user-api/auth/signup 
Content-Type: application/json

{   
    "userType":"user",
    "username": "new_user",
    "email": "new@example.com",
    "password": "secureword123",
    "name": "new user",
    "phone": "+1234567890",
    "address": "fhde street,abc",
    "cart":[],
    "orders":[]
}

###Register a new admin
POST http://localhost:5000/admin-api/auth/signup 
Content-Type: application/json

{
    "userType":"admin",
    "username": "johnny_ohnny",
    "email": "johnny@example.com",
    "password": "securepassword12",
    "name": "Johnny",
    "phone": "+1234567890",
    "address": "abc street,abc"
}


###Sign in (Authenticate user)
POST http://localhost:5000/user-api/auth/login 
Content-Type: application/json

{
    "userType":"user",
    "username": "new_user",
    "password": "secureword123"
}

###Sign in (Authenticate admin)
POST http://localhost:5000/admin-api/auth/login 
Content-Type: application/json

{
    "userType":"admin",
    "username": "johnnyo",
    "password": "securepassword12"
}


###Get user profile
GET http://localhost:5000/user-api/users/new_user 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld191c2VyIiwiaWF0IjoxNzQzNTM1NDA1fQ.KCvoomdF20p4ilDNaISZApSuGEMX1Oave9Rzpz_YbAk

###Update user profile
PUT http://localhost:5000/user-api/users/john_doe 
Content-Type: application/json

{
    "email": "newemail@example.com",
    "name": "John Doe Updated new",
    "phone": "+1234567899",
    "address": "Updated Address, City, Country"
}

###Get user’s cart
GET http://localhost:5000/user-api/users/67ec3d268740fb6168961d84/cart 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld191c2VyIiwiaWF0IjoxNzQzNTM1NDA1fQ.KCvoomdF20p4ilDNaISZApSuGEMX1Oave9Rzpz_YbAk

###Add item to cart
POST http://localhost:5000/user-api/users/67ec3d268740fb6168961d84/cart 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld191c2VyIiwiaWF0IjoxNzQzNTM1NDA1fQ.KCvoomdF20p4ilDNaISZApSuGEMX1Oave9Rzpz_YbAk

{
    "artId": "67eacf83f17206741b0dcb22",
    "quantity":3,
    "deleted":false
}

###Remove item from cart
PUT http://localhost:5000/user-api/users/67ec3d268740fb6168961d84/cart/67eacf83f17206741b0dcb22
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld191c2VyIiwiaWF0IjoxNzQzNTM1NDA1fQ.KCvoomdF20p4ilDNaISZApSuGEMX1Oave9Rzpz_YbAk


###Get user’s order history(Orders Requests)
GET http://localhost:5000/user-api/users/67ec3d268740fb6168961d84/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld191c2VyIiwiaWF0IjoxNzQzNTM1NDA1fQ.KCvoomdF20p4ilDNaISZApSuGEMX1Oave9Rzpz_YbAk

###Place an order
POST http://localhost:5000/user-api/users/67ec3d268740fb6168961d84/orders 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld191c2VyIiwiaWF0IjoxNzQzNTM1NDA1fQ.KCvoomdF20p4ilDNaISZApSuGEMX1Oave9Rzpz_YbAk

{
    "items":[
        {
            "artsId":"67eacf83f17206741b0dcb22",
            "quantity":100
        }
    ],
    "totalPrice":50000,
    "status":"Pending",
    "orderTime":"{{$datetime iso8601}}",
    "modifyTime":"{{$datetime iso8601}}"
}


###Track Order
GET http://localhost:5000/user-api/orders/67ec4a0332ac60a0fe204199
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld191c2VyIiwiaWF0IjoxNzQzNTM1NDA1fQ.KCvoomdF20p4ilDNaISZApSuGEMX1Oave9Rzpz_YbAk

###Cancel Order
PUT http://localhost:5000/user-api/orders/67ec4a0332ac60a0fe204199
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld191c2VyIiwiaWF0IjoxNzQzNTM1NDA1fQ.KCvoomdF20p4ilDNaISZApSuGEMX1Oave9Rzpz_YbAk

{
    "status":"Cancelled",
    "modifyTime":"{{$datetime iso8601}}"
}
###Get gallery
GET http://localhost:5000/user-api/gallery 

###Get single artwork details
GET http://localhost:5000/user-api/gallery/67eacae69151f5c4e1c0418d

###Like an artwork
PUT http://localhost:5000/user-api/gallery/67eacae69151f5c4e1c0418d/like
Content-Type: application/json

{
    "like": true
}


###Get all events
GET http://localhost:5000/user-api/events 


###Get event details
GET http://localhost:5000/user-api/events/67ead3def17206741b0dcb27

###Get all courses
GET http://localhost:5000/user-api/courses 

###Get course details
GET http://localhost:5000/user-api/courses/67eacaf5dc157ee24c8e3f28

###Submit help request
POST http://localhost:5000/user-api/helpQueries 
Content-Type: application/json

{
    "username": "123456",
    "message": "I need help with my account access.",
    "subject": "Account Issues",
    "timestamp": "{{$datetime iso8601}}",
    "deleted":false
}


### Add new artwork  (admin requests)
POST http://localhost:5000/admin-api/gallery  
Content-Type: application/json

{
    "title": "Sunset Bliss new",
    "artist": "John Doe",
    "description": "A beautiful sunset over the mountains.",
    "price": 200,
    "likes": 0,
    "deleted": false
}



### Update/Delete artwork  
PUT http://localhost:5000/admin-api/gallery/67ea512fd89768c8a99bdf71  
Content-Type: application/json

{
    "title": "Sunset Bliss new",
    "price": 15346,
    "deleted": false
}

### Create new event  
POST http://localhost:5000/admin-api/events  
Content-Type: application/json

{
    "title": "My chill event",
    "startDate": "2024-06-15T00:00:00.000Z",
    "endDate":"2024-06-20T00:00:00.000Z",
    "location": "New York, USA",
    "description": "An exclusive art event featuring top artists.",
    "deleted":false
}


### Update event details  
PUT http://localhost:5000/admin-api/events/67eacfbbf17206741b0dcb23 
Content-Type: application/json

{
    "title": "My chill - Super Updated",
    "location":"Hyderabad",
    "deleted": false
}


### Create new course  
POST http://localhost:5000/admin-api/courses  
Content-Type: application/json

{
    "title": "Some Techniques",
    "instructor": "Jane Doe",
    "duration": "27 weeks",
    "price": 100,
    "loaction":"Warangal",
    "mode":"Online & Offline",
    "deleted":false
}

### Update/delete course details  
PUT http://localhost:5000/admin-api/courses/67eacfbbf17206741b0dcb23
Content-Type: application/json

{
    "price": 5000,
    "deleted": false
}

### Get all help queries  
GET http://localhost:5000/admin-api/helpQueries  

### Delete a help query  
PUT http://localhost:5000/admin-api/helpQueries/67ea532bd89768c8a99bdf74
Content-Type: application/json

{
    "deleted": true
}
 
