require('dotenv').config();
const mongoose = require('mongoose');
const GalleryItem = require('../models/GalleryItem');

// ✅ Connect to MongoDB Atlas using your .env file
mongoose.connect(process.env.MONGO_URI)
  .then(() => {
    console.log('✅ Connected to MongoDB Atlas');
    return GalleryItem.insertMany(products);
  })
  .then(() => {
    console.log('🎉 Gallery items imported successfully!');
    return mongoose.disconnect();
  })
  .catch(err => {
    console.error('❌ Error importing gallery items:', err);
    mongoose.disconnect();
  });

// 🖼️ Your gallery items array
const products = [
  // ...your products array...
  {
    id: 1,
    image: 'https://imgur.com/GpaDEUw.jpg',
    title: 'Maheshwara',
    description: 'Lord of the gods, He who is the Lord of the universe.Mahā means "Great" and Īśvara means "lord", hence the name Maheśvara means "the great lord".',
    price: '',
    medium: 'charcoal',
    category: 'Divine Portrait',
  },
  {
    id: 2,
    image: 'https://imgur.com/EpMvMGr.jpg',
    title: 'Vinayaka',
    description: 'The black bold strokes represent the strength and wisdom of Lord vinayaka. The fine detailings brings the complete faith, he guides you towards the right path. He gives you the courage to conquer your fears and overcome all obstacles in your life.',
    price: '',
    medium: 'charcoal',
    category: 'Divine Portrait',
  },
  {
    id: 3,
    image: 'https://imgur.com/D9v7Mz9.jpg',
    title: 'Goddess Gaja Lakshmi matha',
    description: 'Devi Lakshmi, wife of Lord Vishnu and the presiding deity over wealth and resources of any nature, sits on a pristine gaja (elephant). From the chaturbhujadharini (four-armed) aspect to the lalitasana stance (the arrangement of the legs), the familiarity and simplicity of the Devi art makes us fixative and No matter how long you look at it  feels less.Medium : charcoal Category: realistic',
    price: '',
    medium: 'charcoal',
    category: 'Divine Portrait',
  },
  {
    id: 4,
    image: 'https://imgur.com/2O37lPs.jpg',
    title: 'Adhiyogi (The source of Yoga)',
    description: 'The black bold strokes represent the strength and wisdom of Lord vinayaka. The fine detailings brings the complete faith, he guides you towards the right path. He gives you the courage to conquer your fears and overcome all obstacles in your life.',
    price: '',
    medium: 'charcoal on watercolor sheet',
    category: 'Divine Portrait',
  },
  {
    id: 5,
    image: 'https://imgur.com/F9fBXFf.jpg',
    title: 'Hare Krishna',
    description: 'No one can see his or her pure soul, but the one who chants hare krishna. That is what the happiness of hare krishna',
    medium: 'charcoal on watercolor sheet',
    price: '',
    category: 'Divine Portrait',
  },
  {
    id: 6,
    image: 'https://imgur.com/wiT6DNb.jpg',
    title: 'Mata - Sri Hamsa Vahini',
    description: 'A hamsa or swan is often located next to her feet. The sacred bird, if offered a mixture of milk and water, is said to be able to drink the milk alone. It thus symbolizes discrimination between the good and the bad or the eternal and the evanescent. Due to her association with the bird, Saraswati is also referred to as Hamsavahini, which means “she who has a hamsa as her vehicle”. She is usually depicted near a flowing river, which may be related to her early history as a river goddess.',
    price: '',
    medium: 'Graphite',
    category: 'Divine Portrait',
  },
  {
    id: 7,
    image: 'https://imgur.com/q07QYmQ.jpg',
    title: 'Nandeeshwara',
    description: '',
    price: '',
    medium: 'charcoal',
    category: 'Divine Portrait',
  },
  {
    id: 8,
    image: 'https://imgur.com/24WL1Si.jpg',
    title: 'Achintya Ganapati',
    description: 'A rare form of Ganesha. It is in the honour of Lord Murugan (Karthikeya) where he is shown in a very dreadful way with contemporary strokes of Charcoal🙏✨',
    price: '',
    medium: 'charcoal', 
    category: 'Divine Portrait',
  },
  {
    id: 9,
    image: 'https://imgur.com/rEqpGL6.jpg',
    title: 'Devi and Shakthi',
    description: 'She the refuge, peaceful and merciful undoubtedly, She pervades over all, is universal form certainly, Her lotus feet worshipped by universe – all Glory, On your appeal “Protect me Durga” saves entirely.',
    price: '',
    medium: 'charcoal and soft pastels', 
    category: 'Divine Portrait',
  },
  {
    id: 10,
    image: 'https://imgur.com/RC47oZM.jpg',
    title: 'The Awakened One - Goutam Buddha',
    description: 'Buddha, the enlightened teacher and spiritual leader, revolutionized religious thought with his teachings on compassion, mindfulness, ...Buddha s timeless teachings, emphasizing inner peace, compassion, and mindfulness, continue to inspire and guide generations.',
    price: '',
    medium: 'graphite on watercolor sheet',
    category: 'Divine Portrait',
  },
  // Add more products with appropriate categories
  {
    id: 11,
    image: 'https://imgur.com/2lh8MNj.jpg',
    title: '',
    description: '',
    price: '',
    medium: 'graphite on watercolor sheet',
    category: 'Human Portrait',
  },
  {
    id: 12,
    image: 'https://imgur.com/uwMQ88x.jpg',
    title: '',
    description: '',
    price: '',
    medium: 'graphite on watercolor sheet',
    category: 'Human Portrait',
  },
  {
    id: 13,
    image: 'https://imgur.com/9T5H5H2.jpg',
    title: '',
    description: '',
    price: '',
    medium: 'graphite on watercolor sheet',
    category: 'Human Portrait',
  },
  {
    id: 14,
    image: 'https://imgur.com/wMC7woy.jpg',
    title: '',
    description: '',
    price: '',
    medium: 'graphite on watercolor sheet',
    category: 'Human Portrait',
  },
  {
    id: 15,
    image: 'https://imgur.com/jnJ2ryv.jpg',
    title: '',
    description: '',
    price: '',
    medium: 'graphite on watercolor sheet',
    category: 'Human Portrait',
  },
  {
    id: 16,
    image: 'https://imgur.com/EPw7HqN.jpg',
    title: '',
    description: '',
    price: '',
    medium: 'graphite on watercolor sheet',
    category: 'Human Portrait',
  },
  {
    id: 17,
    image: 'https://imgur.com/C7zE3qI.jpg',
    title: '',
    description: '',
    price: '',
    medium: 'graphite on watercolor sheet',
    category: 'Human Portrait',
  },
  {
    id: 18,
    image: 'https://imgur.com/jeSnip4.jpg',
    title: '',
    description: '',
    price: '',
    medium: 'graphite on watercolor sheet',
    category: 'Human Portrait',
  },
  {
    id: 19,
    image: 'https://imgur.com/eQH1Pye.jpg',
    title: '',
    description: '',
    price: '',
    medium: 'graphite on watercolor sheet',
    category: 'Human Portrait',
  },
  {
    id: 20,
    image: 'https://imgur.com/x4Wjf0b.jpg',
    title: '',
    description: '',
    price: '',
    medium: 'graphite on watercolor sheet',
    category: 'Human Portrait',
  },
  {
    id: 21,
    image: 'https://imgur.com/gWWaLMy.jpg',
    title: 'The silent soul',
    description: 'The soul always knows what to do to heal itself. The challenge is to silence the mind!!',
    price: '',
    medium: 'Graphite',
    category: 'Realistic Art',
  },
  {
    id: 22,
    image: 'https://imgur.com/nMJMhBY.jpg',
    title: 'The Butterfly Strokes',
    description: 'The butterfly s shadow dances in harmony with its grace, reminding us that even in our darkest moments, beauty can still prevail." 🦋✨',
    price: '',
    medium: 'Charcoal ',
    category: 'Realistic Art',
  },
  {
    id: 23,
    image: 'https://imgur.com/lyb1Y5i.jpg',
    title: 'The Artistic Eye',
    description: 'The artist, to express her innermost emotions and pain, found her unique form of self-expression: Eye artwork!! Her eyes, windows to her soul, served as both her canvas and medium... With each stroke of her pencil and delicate application of strokes she translated her pain into hauntingly beautiful pieces of art.',
    price: '',
    medium: 'Charcoal',
    category: 'Realistic Art',
  },
  {
    id: 24,
    image: 'https://imgur.com/y7ADSNo.jpg',
    title: 'Dew',
    description: 'A leaf adorned with delicate water droplets. 🍃✏️',
    price: '',
    medium: 'Graphite & Charcoal',
    category: 'Realistic Art',
  },
  {
    id: 25,
    image: 'https://imgur.com/rqOciDb.jpg',
    title: 'The Black Beauty Daisy',
    description: 'Blooming beauty captured in charcoal: A Daisy s delicate allure brought to life on paper. 🌼✨',
    price: '',
    medium: 'Charcoal',
    category: 'Realistic Art',
  },
  {
    id: 26,
    image: 'https://imgur.com/Quklq4o.jpg',
    title: 'The Lotus',
    description: 'Capturing the essence of purity with each charcoal stroke. In the quiet whispers of pencil art, the Lotus unfolds its story—a delicate dance of beauty and resilience. ',
    price: '',
    medium: 'Charcoal',
    category: 'Realistic Art',
  },
  {
    id: 27,
    image: 'https://imgur.com/Vmga0y5.jpg',
    title: 'Emotions Encased in a Glassy Prism',
    description: 'Within the eyes lies an untold story; the ache of the heart veiled by an unshed tear. Encased in a glassy prism, revealing the unspoken depths beneath the surface.',
    price: '',
    medium: 'Charcoal',
    category: 'Realistic Art',
  },
  {
    id: 28,
    image: 'https://imgur.com/i7EDkh1.jpg',
    title: 'Artistic Freedom',
    description: 'Empower the artist s soul, for the truest masterpieces thrives in the wings of freedom ',
    price: '',
    medium: 'Charcoal',
    category: 'Realistic Art',
  },
  {
    id: 29,
    image: 'https://imgur.com/BlvUol7.jpg',
    title: 'Wet cherries',
    description: 'In the cherries blossom shade there s no such thing as a stranger....',
    price: '',
    medium: 'Charcoal on grey sheet',
    category: 'Realistic Art',
  },
  {
    id: 30,
    image: 'https://imgur.com/3KplxUZ.jpg',
    title: 'The Stunning Dark Forest',
    description: 'Embracing Nature s Light: Charcoal brings the forest to life, with sunlight piercing through the trees. ',
    price: '',
    medium: 'Charcoal',
    category: 'Realistic Art',
  },
  {
    id: 31,
    image: 'https://imgur.com/yKEfcQK.jpg',
    title: '',
    description: '',
    price: '',
    medium: 'Charcoal',
    category: 'Animal Portrait',
  },
  {
    id: 32,
    image: 'https://imgur.com/jDhk2iD.jpg',
    title: 'The Charile',
    description: '',
    price: '',
    medium: 'Charcoal',
    category: 'Animal Portrait',
  },
  {
    id: 33,
    image: 'https://imgur.com/w1N487k.jpg',
    title: 'The grey golden Heron',
    description: 'Large, tall, heavy-billed bird with a golden-orange to white-colored plumage that typically keeps its head and neck upright in a majestic pose.',
    price: '',
    medium: 'Charcoal',
    category: 'Animal Portrait',
  },
  {
    id: 34,
    image: 'https://imgur.com/kkpk6ZQ.jpg',
    title: '',
    description: '',
    price: '',
    medium: 'Charcoal',
    category: 'Animal Portrait',
  },
  {
    id: 35,
    image: 'https://imgur.com/yLp15ZH.jpg',
    title: 'Cape marguerite',
    description: 'Blooming fantasies on canvas—where every petal tells a story. 🌺🎨📖 ',
    price: '',
    medium: 'soft pastel colours',
    category: 'Coloured Art',
  },
  {
    id: 36,
    image: 'https://imgur.com/ofxKBdz.jpg',
    title: 'Nature s Ballet',
    description: 'Bird and Bloom Unleashed with the unique brush strokes of blue paint',
    price: '',
    medium: 'Poster colours',
    category: 'Coloured Art',
  },
  {
    id: 37,
    image: 'https://imgur.com/92SLa7l.jpg',
    title: 'The Faded Leaf',
    description: 'They tell you to turn into a new leaf🌿 and then complain about your faded colour.',
    price: '',
    medium: 'Poster colours on black sheet',
    category: 'Coloured Art',
  },
  {
    id: 38,
    image: 'https://imgur.com/7wN1IhF.jpg',
    title: 'Rose',
    description: 'Meet my freshly painted rose! 🌺 Adding a pop of color to your day!!',
    price: '',
    medium: 'Water colour brush pens',
    category: 'Coloured Art',
  },
  {
    id: 39,
    image: 'https://imgur.com/0IDyft2.jpg',
    title: 'Abstract form of Lambodhara',
    description: 'Lord Ganesha is fondly called "Lambodara", which means a large belly. This represents endurance and risk-taking capability.',
    price: '',
    medium: 'Soft Pastels',
    category: 'Coloured Art',
  },
  {
    id: 40,
    image: 'https://imgur.com/5GY3tvM.jpg',
    title: 'Cape marguerite',
    description: 'Blooming fantasies on canvas—where every petal tells a story. 🌺🎨📖 ',
    price: '',
    medium: 'soft pastel colours',
    category: 'Coloured Art',
  },
  {
    id: 41,
    image: 'https://imgur.com/I9zeMcs.jpg',
    title: 'HeARTist',
    description: 'Where Art and Heart Unite 🎨❤️ A brushstroke of passion, a pencil sketch of emotion, it is the artist s heart that creates the masterpiece.',
    price: '',
    medium: 'Colour pencils ',
    category: 'Coloured Art',
  },
  {
    id: 42,
    image: 'https://imgur.com/irIucMW.jpg',
    title: 'Flamingo',
    description: 'You are a rare bird, just like a flamingo.” “Embrace your uniqueness, just like a flamingo in a flock.” “Flamingos symbolize balance and poise.” “Flamingos teach us to find beauty in both stillness and movement.” “Do not be afraid to stand out from the crowd, just like a flamingo.',
    price: '',
    medium: 'Poster Colours',
    category: 'Coloured Art',
  },
  {
    id: 43,
    image: 'https://imgur.com/7XF2ncg.jpg',
    title: 'The Blue Fall',
    description: 'Catch your breath in colours of the waterfall Dipping brushes in nature s flow: Capturing the beauty of waterfalls on canvas. 🎨🌊 "Let the water teach you tranquility, and the falls inspire your journey." 💙 💦🌊',
    price: '',
    medium: 'Poster Colours',
    category: 'Coloured Art',
  },
  {
    id: 44,
    image: 'https://res.cloudinary.com/dw1ajw27r/image/upload/v1744724160/samples/cup-on-a-table.jpg',
    title: 'The Long Trunk',
    description: 'In the gentle giant s presence, we discover true magnificence. 🐘🎨 "The elephant is a masterpiece of divine creation, a symbol of strength, wisdom, and the intricate tapestry of life ',
    price: '',
    medium: 'Graphite',
    category: 'Animal Portrait',
  },
];
